
version: "3.6"

services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: secret
            PGDATA: /var/lib/postgresql/data
        volumes:
            - /home/uad/develop/dashboard-global/data/db:/var/lib/postgresql/data
        ports:
            - "5432:5432"
 
    pgadmin:
        image: dpage/pgadmin4:latest
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: averneus@gmail.com
            PGADMIN_DEFAULT_PASSWORD: secret
            PGADMIN_LISTEN_PORT: 80
        ports:
            - "8080:80"
        volumes:
            - /home/uad/develop/dashboard-global/data/pgadmin:/var/lib/pgadmin
        links:
            - "db:pgsql-server"
#volumes:
#    /home/uad/develop/dashboard-global/data/db:
#    /home/uad/develop/dashboard-global/data/pgadmin: